package cl.streambox.tv;

import android.content.Context;
import android.content.SharedPreferences;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Pattern;

/** User-facing configuration for Highfly Premium playback and List 4 events. */
public final class HighflyPremiumPreferences {
    public static final String KEY_ENABLED = "highfly_premium_enabled";
    public static final String KEY_INCLUDE_EVENTS = "highfly_premium_include_events";
    public static final String KEY_SELECTED_EVENT_IDS = "highfly_premium_selected_event_ids";
    public static final String KEY_REGION = "highfly_premium_region";
    public static final String KEY_STREAM_SORT = "highfly_premium_stream_sort";
    /** Public stable metadata list generated by the Lista M3U GitHub runner. */
    public static final String STABLE_PLAYLIST_URL =
            "https://raw.githubusercontent.com/SPxMM3R1/lista-m3u/main/3.m3u";
    private static final String EVENT_ID_SEPARATOR = ";";
    private static final Pattern SAFE_EVENT_ID = Pattern.compile(
            "(?i)^(?:streamed|sf):[a-z0-9][a-z0-9:_-]{1,159}$"
    );

    private HighflyPremiumPreferences() {}

    public enum Region {
        MAIN("main", "Principal", "https://premium.highfly.dev"),
        US1("us1", "US-1", "https://premium-us1.highfly.dev"),
        US2("us2", "US-2", "https://premium-us2.highfly.dev"),
        EU1("eu1", "Europa", "https://premium-eu1.highfly.dev");

        private final String preferenceValue;
        private final String displayName;
        private final String baseUrl;

        Region(String preferenceValue, String displayName, String baseUrl) {
            this.preferenceValue = preferenceValue;
            this.displayName = displayName;
            this.baseUrl = baseUrl;
        }

        public String getPreferenceValue() {
            return preferenceValue;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getBaseUrl() {
            return baseUrl;
        }

        static Region fromHost(String host) {
            if (host == null) return null;
            String normalized = host.trim();
            for (Region region : values()) {
                try {
                    if (java.net.URI.create(region.baseUrl).getHost().equalsIgnoreCase(normalized)) {
                        return region;
                    }
                } catch (IllegalArgumentException ignored) {
                    // The enum constants are compile-time URLs; keep this
                    // defensive in case a future value is edited incorrectly.
                }
            }
            return null;
        }

        public static Region fromPreference(String value) {
            if (value != null) {
                for (Region region : values()) {
                    if (region.preferenceValue.equalsIgnoreCase(value.trim())) {
                        return region;
                    }
                }
            }
            return MAIN;
        }
    }

    public enum StreamSort {
        DEFAULT("default", "Orden del proveedor"),
        HIGHEST_FIRST("quality-high", "Mayor calidad primero"),
        LOWEST_FIRST("quality-low", "Inicio más rápido");

        private final String preferenceValue;
        private final String displayName;

        StreamSort(String preferenceValue, String displayName) {
            this.preferenceValue = preferenceValue;
            this.displayName = displayName;
        }

        public String getPreferenceValue() {
            return preferenceValue;
        }

        public String getDisplayName() {
            return displayName;
        }

        public static StreamSort fromPreference(String value) {
            if (value != null) {
                for (StreamSort sort : values()) {
                    if (sort.preferenceValue.equalsIgnoreCase(value.trim())) {
                        return sort;
                    }
                }
            }
            return HIGHEST_FIRST;
        }
    }

    public static boolean isEnabled(Context context) {
        return preferences(context).getBoolean(KEY_ENABLED, false);
    }

    public static boolean includeEvents(Context context) {
        return preferences(context).getBoolean(KEY_INCLUDE_EVENTS, false);
    }

    /**
     * Returns the event IDs selected by the user. IDs are catalog identities,
     * never signed playback URLs, so they are safe to keep as preferences.
     */
    public static Set<String> selectedEventIds(Context context) {
        String stored = preferences(context).getString(KEY_SELECTED_EVENT_IDS, "");
        if (stored == null || stored.isBlank()) return Collections.emptySet();
        LinkedHashSet<String> result = new LinkedHashSet<>();
        for (String value : stored.split(EVENT_ID_SEPARATOR)) {
            String id = value == null ? "" : value.trim();
            if (SAFE_EVENT_ID.matcher(id).matches()) result.add(id);
        }
        return Collections.unmodifiableSet(result);
    }

    public static void saveSelectedEventIds(Context context, Set<String> eventIds) {
        LinkedHashSet<String> safeIds = new LinkedHashSet<>();
        if (eventIds != null) {
            for (String value : eventIds) {
                String id = value == null ? "" : value.trim();
                if (SAFE_EVENT_ID.matcher(id).matches()) safeIds.add(id);
            }
        }
        StringBuilder serialized = new StringBuilder();
        for (String id : safeIds) {
            if (serialized.length() > 0) serialized.append(EVENT_ID_SEPARATOR);
            serialized.append(id);
        }
        preferences(context).edit()
                .putString(KEY_SELECTED_EVENT_IDS, serialized.toString())
                .apply();
    }

    /** Removes one unavailable event without changing the other selections. */
    public static void removeSelectedEventId(Context context, String eventId) {
        String safeId = eventId == null ? "" : eventId.trim();
        if (!SAFE_EVENT_ID.matcher(safeId).matches()) return;
        LinkedHashSet<String> selected = new LinkedHashSet<>(selectedEventIds(context));
        if (selected.remove(safeId)) saveSelectedEventIds(context, selected);
    }

    public static Region region(Context context) {
        return Region.fromPreference(preferences(context).getString(
                KEY_REGION,
                Region.MAIN.getPreferenceValue()
        ));
    }

    public static StreamSort streamSort(Context context) {
        return StreamSort.fromPreference(preferences(context).getString(
                KEY_STREAM_SORT,
                StreamSort.HIGHEST_FIRST.getPreferenceValue()
        ));
    }

    /**
     * A source signature that contains no credential material. The generation
     * is process-local and changes whenever the user replaces or clears the
     * Premium credential, which invalidates event/playback state without
     * putting a token or token hash into a persistent configuration. The
     * stable List 3 metadata itself is fetched through PlaylistRepository.
     */
    static String sourceSignature(Context context, HighflyPremiumCredentialStore store) {
        return "enabled=" + isEnabled(context)
                + ";events=" + includeEvents(context)
                + ";selectedEvents=" + selectedEventIds(context)
                + ";region=" + region(context).getPreferenceValue()
                + ";sort=" + streamSort(context).getPreferenceValue()
                + ";credentialGeneration=" + (store == null ? 0L : store.getGeneration());
    }

    private static SharedPreferences preferences(Context context) {
        return context.getSharedPreferences(SettingsActivity.PREFS, Context.MODE_PRIVATE);
    }
}
